### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by ext5** [gabsoftware/GabNetStats#1]
Could you include the Russian language file in your project?
[ru.zip](https://github.com/gabsoftware/GabNetStats/files/2851499/ru.zip)

**Comment by gabsoftware** [comment]
Hi Valerij!

Thanks for the language pack, I will include it in the next release and you will be credited as the Russian language maintainer.

Best regards,

Gabriel

Le 11 février 2019 22:42:22 GMT+08:00, Valerij Romanovskij <notifications@github.com> a écrit :
>Could you include the Russian language file in your project?
>[ru.zip](https://github.com/gabsoftware/GabNetStats/files/2851499/ru.zip)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabsoftware/GabNetStats/issues/1

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabsoftware** [comment]
Hi Valerij,
I'd be happy to add the Russian translation to GabNetStats.
But I cannot include an externally compiled DLL, I don't know what is inside, for all I know it could be a malware.
Could you grab the sources at https://github.com/gabsoftware/GabNetStats (https://github.com/gabsoftware/GabNetStats) and propose a pull request (sources only, do not include the .dll) ?
Thanks!
Best regards,
Gabriel Hautclocq
On lun., févr. 11, 2019 at 15:42, Valerij Romanovskij  wrote: Could you include the Russian language file in your project?
ru.zip (https://github.com/gabsoftware/GabNetStats/files/2851499/ru.zip)

**Comment by ext5** [comment]
For translation, I used program Radialix 2.14.01(build 3893). The project Radialix seems to be long dead, but I have successfully and for a long time with this program do localization resources of the various programs. With this program, translating resources is very simple.
![image 1](https://user-images.githubusercontent.com/8058418/53025168-7aefde80-3471-11e9-94b5-45fc9a110714.jpg)
there is no malware inside.
This is a file of the Radialix project, 
[GabNetStats.zip](https://github.com/gabsoftware/GabNetStats/files/2880606/GabNetStats.zip)
I don’t know more than help. I don’t know how to work with sources, I'm not a programmer.

**Comment by gabsoftware** [comment]
Thanks for the radialix source file, I will add your translation today "the Visual Studio way" :-)

**Comment by gabsoftware** [comment]
I added the Russian translation :-)
Many thanks for your work, that was quite a lot of strings to translate! 👍
I added your name to the Readme.md in the Thanks section.
You can grab the new release here: https://github.com/gabsoftware/GabNetStats/releases
Thanks again!

**Comment by gabsoftware** [comment]
Closing the issue as the translation has been added. Please reopen if there are any issues.
